---

root: true

env:
  es6: true
  browser: false
  mocha: false
  node: true

rules:
  brace-style: [error, 1tbs]
  indent: [error, 4, {VariableDeclarator: 2}]
  no-var: error
  one-var: [error, {initialized: never, uninitialized: always}]
  prefer-const: error
